name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'adopt'

    - name: create properties file
      run: touch ./src/test/resources/config.properties

    - name: write to properties file
      env:
        USERNAME: ${{ secrets.username }}
        PASSWORD: ${{ secrets.password }}
        BASE_URI: ${{ secrets.base_uri }}
      run: |
        echo "username=${USERNAME}" >> ./src/test/resources/config.properties
        echo "password=${PASSWORD}" >> ./src/test/resources/config.properties
        echo "base_uri=${BASE_URI}" >> ./src/test/resources/config.properties
        echo "token=ToBeRetrieved" >> ./src/test/resources/config.properties
        echo "token_retrieved=2024-04-25T13:00:00" >> ./src/test/resources/config.properties

    - name: View properties file
      run: cat ./src/test/resources/config.properties
    
    - name: Build and test with Maven
      run: mvn -B package --file pom.xml
      working-directory: .
